---
apiVersion: zitadel.mojaloop.io/v1alpha1
kind: ZitadelProviderConfig
metadata:
  name: zitadel-provider
  namespace: ${ARGOCD_ENV_zitadel_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: 0
spec:
  parameters:
    domain: "zitadel.${ARGOCD_ENV_zitadel_dns_subdomain}"
    providerConfigName: "zitadel-provider"
  providerConfigsRef:
    kubernetesProviderName: "kubernetes-provider"
