apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - virtual-services.yaml
  - testvsjob.yaml

helmCharts:
  - name: zitadel
    releaseName: zitadel
    version: ${ARGOCD_ENV_zitadel_helm_version}
    repo: https://charts.zitadel.com
    valuesFile: zitadel-values.yaml
    namespace: ${ARGOCD_ENV_zitadel_namespace}
