apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_k8s_config_argocd_app_name}
  namespace: ${ARGOCD_ENV_k8s_config_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_k8s_config_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_k8s_config_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_k8s_config_application_gitrepo_tag}
    path: gitops/applications/overlays/k8s_provider/${ARGOCD_ENV_k8s_config_k8s_cluster_type}/
    plugin:
      name: envsubst
      env:
        - name: "zitadel_namespace"
          value: "${ARGOCD_ENV_security_zitadel_namespace}"

        - name: "terraform_modules_tag"
          value: "${ARGOCD_ENV_k8s_config_application_gitrepo_tag}"

        - name: "zitadel_grant_prefix"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_grant_prefix}"

        - name: "zitadel_dns_subdomain"
          value: "${ARGOCD_ENV_security_zitadel_dns_subdomain}"

        - name: "argocd_namespace"
          value: "${ARGOCD_ENV_utils_argocd_helm_namespace}"

        - name: "k8s_admin_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_k8s_admin_rbac_group}"

        - name: "k8s_user_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_k8s_user_rbac_group}"
        
        - name: "crossplane_namespace"
          value: "${ARGOCD_ENV_utils_crossplane_namespace}"

        - name: "k8s_config_namespace"
          value: "${ARGOCD_ENV_k8s_config_namespace}"

        - name: "cluster_name"
          value: "${ARGOCD_ENV_k8s_config_eks_name}"

        - name: "cloud_region"
          value: "${ARGOCD_ENV_k8s_config_k8s_cloud_region}"
        
        - name: "zitadel_post_config_output_secret"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_post_config_output_secret}"

        - name: "zitadel_tf_provider_version"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_tf_provider_version}"
        
        - name: "aws_tf_provider_version"
          value: "${ARGOCD_ENV_k8s_config_aws_tf_provider_version}"