apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "${ARGOCD_ENV_utils_storage_post_config_app_name}"
  namespace: ${ARGOCD_ENV_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: "${ARGOCD_ENV_utils_storage_post_config_sync_wave}"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "${ARGOCD_ENV_utils_storage_namespace}"
  sources:
    - repoURL: ${ARGOCD_ENV_argocd_repo_url}
      targetRevision: ${ARGOCD_ENV_utils_application_gitrepo_tag}
      path: gitops/applications/overlays/cloud_provider/${ARGOCD_ENV_utils_storage_cloud_provider}/storage-provider/storage-post-config
      plugin:
        name: envsubst
        env:
          - name: "storage_namespace"
            value: "${ARGOCD_ENV_utils_storage_namespace}"

          - name: "block_storage_class_name"
            value: "${ARGOCD_ENV_utils_storage_block_storage_class_name}"

          - name: "fs_storage_class_name"
            value: "${ARGOCD_ENV_utils_storage_private_cloud_provider_fs_storage_class_name}"

          - name: "capi_cluster_name"
            value: "${ARGOCD_ENV_utils_capi_capi_cluster_name}"

          - name: "capi_cluster_namespace"
            value: "${ARGOCD_ENV_utils_capi_capi_cluster_namespace}"

          - name: "sc_storage_namespace"
            value: "${ARGOCD_ENV_utils_capi_capi_rook_ceph_namespace}"


