apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_utils_argocd_app_name}-${ARGOCD_ENV_utils_post_config_app_name}
  namespace: ${ARGOCD_ENV_utils_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_utils_post_config_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_utils_app_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_utils_application_gitrepo_tag}
    path: gitops/applications/base/utils-post-config
    plugin:
      name: envsubst
      env:
        - name: "terraform_crossplane_modules_version"
          value: "${ARGOCD_ENV_utils_post_config_terraform_crossplane_modules_version}"

        - name: "vault_crossplane_modules_version"
          value: "${ARGOCD_ENV_utils_post_config_vault_crossplane_modules_version}"

        - name: "ansible_crossplane_modules_version"
          value: "${ARGOCD_ENV_utils_post_config_ansible_crossplane_modules_version}"

        - name: "crossplane_namespace"
          value: "${ARGOCD_ENV_utils_crossplane_namespace}"

        - name: "ec2_crossplane_module_version"
          value: "${ARGOCD_ENV_utils_post_config_ec2_crossplane_module_version}"

        - name: "rds_crossplane_module_version"
          value: "${ARGOCD_ENV_utils_post_config_rds_crossplane_module_version}"

        - name: "crossplane_func_pat_version"
          value: "${ARGOCD_ENV_utils_post_config_crossplane_func_pat_version}"
