apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${ARGOCD_ENV_security_zitadel_app_name}-post-config
  namespace: ${ARGOCD_ENV_security_app_namespace}
  annotations:
    argocd.argoproj.io/sync-wave: ${ARGOCD_ENV_security_zitadel_post_config_sync_wave}

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${ARGOCD_ENV_security_app_namespace}

  source:
    repoURL: ${ARGOCD_ENV_argocd_repo_url}
    targetRevision: ${ARGOCD_ENV_security_application_gitrepo_tag}
    path: gitops/applications/base/zitadel-post-config
    plugin:
      name: envsubst
      env:
        - name: "zitadel_release_name"
          value: "${ARGOCD_ENV_security_zitadel_app_name}"

        - name: "zitadel_namespace"
          value: "${ARGOCD_ENV_security_zitadel_namespace}"

        - name: "zitadel_helm_version"
          value: "${ARGOCD_ENV_security_zitadel_helm_version}"

        - name: "zitadel_tf_provider_version"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_tf_provider_version}"

        - name: "terraform_modules_tag"
          value: "${ARGOCD_ENV_security_zitadel_terraform_modules_tag}"

        - name: "vault_rbac_admin_group"
          value: "${ARGOCD_ENV_security_zitadel_vault_rbac_admin_group}"

        - name: "zitadel_grant_prefix"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_grant_prefix}"

        - name: "cockroachdb_helm_version"
          value: "${ARGOCD_ENV_security_cockroachdb_helm_version}"

        - name: "cockroachdb_pvc_size"
          value: "${ARGOCD_ENV_security_cockroachdb_pvc_size}"

        - name: "cockroachdb_release_name"
          value: "${ARGOCD_ENV_security_cockroachdb_app_name}"

        - name: "zitadel_istio_gateway_namespace"
          value: "${ARGOCD_ENV_security_zitadel_istio_gateway_namespace}"

        - name: "zitadel_istio_wildcard_gateway_name"
          value: "${ARGOCD_ENV_security_zitadel_istio_wildcard_gateway_name}"

        - name: "zitadel_dns_subdomain"
          value: "${ARGOCD_ENV_security_zitadel_dns_subdomain}"

        - name: "zitadel_post_config_output_secret"
          value: "${ARGOCD_ENV_security_zitadel_zitadel_post_config_output_secret}"

        - name: "vault_tf_post_config_output_secret"
          value: "${ARGOCD_ENV_vault_vault_vault_tf_post_config_output_secret}"

        - name: "vault_keys_secret"
          value: "${ARGOCD_ENV_vault_vault_vault_keys_secret}"

        - name: "vault_namespace"
          value: "${ARGOCD_ENV_vault_vault_namespace}"

        - name: "vault_tf_provider_version"
          value: "${ARGOCD_ENV_vault_vault_vault_tf_provider_version}"

        - name: "argocd_namespace"
          value: "${ARGOCD_ENV_utils_argocd_helm_namespace}"

        - name: "argocd_oidc_secret"
          value: "${ARGOCD_ENV_security_zitadel_argocd_oidc_secret}"

        - name: "argocd_admin_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_argocd_admin_rbac_group}"

        - name: "argocd_user_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_argocd_user_rbac_group}"

        - name: "argocd_dns_subdomain"
          value: "${ARGOCD_ENV_utils_argocd_helm_dns_subdomain}"

        - name: "k8s_admin_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_k8s_admin_rbac_group}"

        - name: "k8s_user_rbac_group"
          value: "${ARGOCD_ENV_security_zitadel_k8s_user_rbac_group}"

        - name: "k8s_oidc_post_config_output_secret"
          value: "${ARGOCD_ENV_security_zitadel_k8s_oidc_post_config_output_secret}"
