apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - vault-secrets.yaml
  - netbird-xplane-terraform.yaml

helmCharts:
  - name: stunner-gateway-operator
    releaseName: stunner-gateway-operator
    version: ${ARGOCD_ENV_stunner_gateway_operator_helm_version}
    repo: https://l7mp.io/stunner
    namespace: ${ARGOCD_ENV_stunner_system_namespace}
