env: dev
domain: labsk8s2010.mojaloop.live
cloud_platform: aws
dns_provider: aws
managed_svc_cloud_platform: aws
cloud_platform_client_secret_name: AWS_SECRET_ACCESS_KEY
k8s_cluster_module: base-k8s
cloud_region: eu-west-1
k8s_cluster_type: microk8s
ansible_collection_tag: v5.2.6
iac_terraform_modules_tag: v5.3.4
letsencrypt_email: test@mojalabs.io
dns_zone_force_destroy: true
longhorn_backup_object_store_destroy: true
managed_svc_enabled: false
addons_module_enabled: false
nodes:
  master-generic:
    master: true
    instance_type: "m5.4xlarge"
    node_count: 3
    storage_gbs: 300
    node_taints: []
    node_labels:
      workload-class.mojaloop.io/CENTRAL-LEDGER-SVC: "enabled"
      workload-class.mojaloop.io/CORE-API-ADAPTERS: "enabled"
      workload-class.mojaloop.io/CENTRAL-SETTLEMENT: "enabled"
      workload-class.mojaloop.io/QUOTING-SERVICE: "enabled"
      workload-class.mojaloop.io/ACCOUNT-LOOKUP-SERVICE: "enabled"
      workload-class.mojaloop.io/ALS-ORACLES: "enabled"
      workload-class.mojaloop.io/CORE-HANDLERS: "enabled"
      workload-class.mojaloop.io/KAFKA-CONTROL-PLANE: "enabled"
      workload-class.mojaloop.io/KAFKA-DATA-PLANE: "enabled"
      workload-class.mojaloop.io/RDBMS-CENTRAL-LEDGER-LIVE: "enabled"
      workload-class.mojaloop.io/RDBMS-ALS-LIVE: "enabled"
      workload-class.mojaloop.io/MONITORING: "enabled"
vpc_cidr: "10.106.0.0/23"
managed_vpc_cidr: "10.28.0.0/23"
enable_k6s_test_harness: false
k6s_docker_server_instance_type: "m5.large"
master_node_supports_traffic: true
tags:
  {
    "Origin": "Terraform",
    "mojaloop/cost_center": "mlf-iac-sandbox",
    "mojaloop/env": "ft-sbox-rw",
    "mojaloop/owner": "James-Bush",
  }
gitlab_admin_rbac_group: tenant-admins
gitlab_readonly_rbac_group: tenant-viewers
