tf_version: ">= 1.2"
local_provider_version: "~> 2.4"
gitlab_provider_version: "~> 16.0"
vault_provider_version: "~> 3.16"
cert_manager_chart_version: 1.12.2
consul_chart_version: 1.4.0
longhorn_chart_version: 1.4.4
external_dns_chart_version: 6.24.1
vault_chart_version: 0.24.1
vault_config_operator_helm_chart_version: 0.8.16
nginx_helm_chart_version: 4.6.1
keycloak_operator_version: 22.0.2
istio_chart_version: 1.18.2
external_secrets_version: 0.8.2
argocd_version: 2.9.7
argocd_lovely_plugin_version: 0.18.0
mcm_enabled: true
mojaloop_enabled: true
pm4ml_enabled: false
prometheus_operator_version: 8.22.8
grafana_operator_version: 3.5.11
grafana_version: 10.2.3
tempo_chart_version: 2.6.0
loki_chart_version: 2.13.0
ory_stack_enabled: true
loki_ingester_pvc_size: 50Gi
prometheus_pvc_size: 50Gi
loki_ingester_retention_period: 72h
prometheus_retention_period: 10d
istio_egress_gateway_max_replicas: 5
microk8s_version: 1.29/stable
alertmanager_enabled: false
