tf_version: ">= 1.2"
local_provider_version: "~> 2.4"
gitlab_provider_version: "~> 16.0"
vault_provider_version: "~> 3.25" # https://github.com/hashicorp/terraform-provider-vault/issues/1900
cert_manager_chart_version: 1.12.2
consul_chart_version: 1.4.0
longhorn_chart_version: 1.6.1
external_dns_chart_version: 6.24.1
vault_chart_version: 0.24.1
vault_config_operator_helm_chart_version: 0.8.16
nginx_helm_chart_version: 4.6.1
keycloak_operator_version: 22.0.2
istio_chart_version: 1.18.2
external_secrets_version: 0.8.2
argocd_version: 2.9.7
argocd_lovely_plugin_version: 0.18.0
mcm_enabled: true
mojaloop_enabled: true
pm4ml_enabled: false
proxy_pm4ml_enabled: false
vnext_enabled: false
grafana_crd_version_tag: v5.6.0
prometheus_crd_version: 8.0.1
prometheus_operator_version: 8.22.8
prometheus_process_exporter_version: 0.4.2
grafana_operator_version: 3.5.11
grafana_version: 10.2.3
grafana_dashboard_tag: v16.3.0-snapshot.24 # TODO: update once v16.1.x is published
tempo_chart_version: 3.1.0
loki_chart_version: 2.13.0
loki_ingester_pvc_size: 10Gi
prometheus_pvc_size: 50Gi
loki_retention_enabled: true
loki_ingester_retention_period: 72h
loki_ingester_max_chunk_age: 2h
prometheus_retention_period: 10d
tempo_retention_period: 72h
istio_egress_gateway_max_replicas: 5
microk8s_version: 1.29/stable
alertmanager_enabled: false
alertmanager_prod_alerts_enabled: false   # if false, alerts are sent to dev alerts slack channel
alertmanager_slack_integration_enabled: false
alertmanager_jira_integration_enabled: false
istio_proxy_log_level: warn
longhorn_backup_job_enabled: false
enable_central_observability_write: false
enable_central_observability_read: false
