common_platform_db:
  app_owner: "platform"
  external_resource_config:
    allow_major_version_upgrade: false
    apply_immediately: false
    password_key_name: common_platform_db_password
    instance_address_key_name: common_platform_db_instance_address
    allocated_storage: 100
    storage_type: io1
    storage_iops: 5000
    backup_retention_period: 1
    backup_window: 01:00-04:00
    db_name: common_platform_db
    deletion_protection: false
    engine: aurora-mysql
    engine_version: 8.0.mysql_aurora.3.04.0
    family: aurora-mysql8.0
    final_snapshot_identifier: common_platform_db_final_snapshot
    instance_class: db.t3.medium
    replicas: 1
    maintenance_window: Sun:04:00-Sun:06:00
    major_engine_version: "8.0"
    monitoring_interval: "30"
    options:
      - option_name: MARIADB_AUDIT_PLUGIN
        option_settings:
          - name: SERVER_AUDIT_EVENTS
            value: CONNECT
          - name: SERVER_AUDIT_FILE_ROTATIONS
            value: "37"
    parameters:
      - name: character_set_client
        value: utf8mb4
      - name: character_set_server
        value: utf8mb4
      - name: innodb_lock_wait_timeout
        value: "120"
      - name: connect_timeout
        value: "600"
      - name: wait_timeout
        value: "600"
      - name: interactive_timeout
        value: "600"
      - name: max_connections
        value: "4000"
      - name: aurora_fwd_writer_max_connections_pct
        value: "30"
    port: "3306"
    skip_final_snapshot: true
    multi_az: false
    storage_encrypted: true
    tags:
      Origin: Terraform
      mojaloop/cost_center: mlf-iac-sandbox
      mojaloop/env: ft-sbox-rw
      mojaloop/owner: Samuel-Kummary
    username: platform
    master_user_password_secret_namespace: stateful-resources
    master_user_password_secret: common-platform-db-secret
    master_user_password_secret_key: password
    logical_service_name: common-platform-db
    logical_service_port: 3306
    vault_master_user_password_secret_key: common_platform_db_password
    vault_instance_address_key: common_platform_db_instance_address
common_mojaloop_db:
  app_owner: "mojaloop"
  external_resource_config:
    allow_major_version_upgrade: false
    apply_immediately: false
    password_key_name: common_mojaloop_db_password
    instance_address_key_name: common_mojaloop_db_instance_address
    allocated_storage: 100
    storage_type: io1
    storage_iops: 5000
    backup_retention_period: 1
    backup_window: 01:00-04:00
    db_name: common_mojaloop_db
    deletion_protection: false
    engine: aurora-mysql
    engine_version: 8.0.mysql_aurora.3.04.0
    family: aurora-mysql8.0
    final_snapshot_identifier: common_mojaloop_db_final_snapshot
    instance_class: db.t3.medium
    replicas: 1
    maintenance_window: Sun:04:00-Sun:06:00
    major_engine_version: "8.0"
    monitoring_interval: "30"
    options:
      - option_name: MARIADB_AUDIT_PLUGIN
        option_settings:
          - name: SERVER_AUDIT_EVENTS
            value: CONNECT
          - name: SERVER_AUDIT_FILE_ROTATIONS
            value: "37"
    parameters:
      - name: character_set_client
        value: utf8mb4
      - name: character_set_server
        value: utf8mb4
      - name: max_connections
        value: "4000"
      - name: aurora_fwd_writer_max_connections_pct
        value: "30"
    port: "3306"
    skip_final_snapshot: true
    multi_az: false
    storage_encrypted: true
    tags:
      Origin: Terraform
      mojaloop/cost_center: mlf-iac-sandbox
      mojaloop/env: ft-sbox-rw
      mojaloop/owner: Samuel-Kummary
    username: mojaloop
    master_user_password_secret_namespace: stateful-resources
    master_user_password_secret: common-mojaloop-db-secret
    master_user_password_secret_key: password
    logical_service_name: common-mojaloop-db
    logical_service_port: 3306
    vault_master_user_password_secret_key: common_mojaloop_db_password
    vault_instance_address_key: common_mojaloop_db_instance_address
common_document_db:
  app_owner: "mojaloop"
  external_resource_config:
    allocated_storage: 100
    allow_major_version_upgrade: false
    apply_immediately: false
    backup_retention_period: 1
    backup_window: 01:00-04:00
    db_name: common_document_db
    delete_protection: false
    engine: docdb
    engine_version: "5.0"
    family: docdb5.0
    final_snapshot_identifier: common_document_db_final_snapshot
    instance_address_key_name: common_document_db_instance_address
    instance_class: db.t3.medium
    maintenance_window: Sun:04:00-Sun:06:00
    major_engine_version: "5.0"
    monitorin_interval: "30"
    multi_az: false
    options: []
    parameters:
      - apply_method: pending-reboot
        name: tls
        value: disabled
    password_key_name: common_document_db_password
    port: "27017"
    replicas: 1
    skip_final_snapshot: true
    storage_encrypted: true
    storage_type: standard
    storage_iops: 5000
    tags:
      Origin: Terraform
      mojaloop/cost_center: mlf-iac-sandbox
      mojaloop/env: ft-sbox-rw
      mojaloop/owner: Samuel-Kummary
    username: mojaloop
    master_user_password_secret_namespace: stateful-resources
    master_user_password_secret: common-mojaloop-db-secret
    master_user_password_secret_key: password
    logical_service_name: common-mongodb
    logical_service_port: 27017
    vault_master_user_password_secret_key: common_mongodb_password
    vault_instance_address_key: common_mongodb_instance_address
