tf_version: ">= 1.2"
local_provider_version: "~> 2.4"
gitlab_provider_version: "~> 16.0"
vault_provider_version: "~> 3.16"
cert_manager_chart_version: 1.12.2
consul_chart_version: 1.1.1
longhorn_chart_version: 1.4.0
external_dns_chart_version: 6.24.1
vault_chart_version: 0.24.1
vault_config_operator_helm_chart_version: 0.8.16
nginx_helm_chart_version: 4.6.1
loki_chart_version: 2.9.10
keycloak_operator_version: 22.0.1
istio_chart_version: 1.18.2
external_secrets_version: 0.8.2
argocd_version: 2.8.2
argocd_lovely_plugin_version: 0.18.0
mcm_enabled: true
mojaloop_enabled: true
pm4ml_enabled: false
