bulk_enabled: false
third_party_enabled: false
mcm_chart_version: 0.7.1
mojaloop_chart_version: 15.2.0-16753.f6d07f6
mcm_ingress_internal_lb: false
mojaloop_ingress_internal_lb: true
#replica counts
account_lookup_service_replica_count: 1
account_lookup_service_admin_replica_count: 1
quoting_service_replica_count: 1
ml_api_adapter_service_replica_count: 1
ml_api_adapter_handler_notifications_replica_count: 1
central_ledger_service_replica_count: 1
central_ledger_handler_transfer_prepare_replica_count: 1
central_ledger_handler_transfer_position_replica_count: 1
central_ledger_handler_transfer_get_replica_count: 1
central_ledger_handler_transfer_fulfil_replica_count: 1
central_ledger_handler_admin_transfer_replica_count: 1
central_settlement_service_replica_count: 1
central_settlement_handler_deferredsettlement_replica_count: 1
central_settlement_handler_grosssettlement_replica_count: 1
central_settlement_handler_rules_replica_count: 1
trasaction_requests_service_replica_count: 1
auth_service_replica_count: 1
consent_oracle_replica_count: 1
tp_api_svc_replica_count: 1
bulk_api-adapter_service_replica_count: 1
bulk_api_adapter_handler_notification_replica_count: 1
cl_handler_bulk_transfer_prepare_replica_count: 1
cl_handler_bulk_transfer_fulfil_replica_count: 1
cl_handler_bulk_transfer_processing_replica_count: 1
cl_handler_bulk_transfer_get_replica_count: 1
onboarding_collection_tag: 15.1.0-iac-snapshot.0
enable_istio_injection: true
