apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-provider-config.yaml
  - kubernetes-provider-config.yaml
  - xr-definition-rds.yaml
  - composition-rds.yaml
  - xr-definition-rds-aurora.yaml
  - composition-rds-aurora.yaml
  - composition-rds-aurora-replica.yaml
  - xr-definition-rds-aurora-replica.yaml
  - composition-aws-s3-bucket.yaml
  - xr-definition-aws-s3-bucket.yaml