apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - objectstore-certs.yaml
  - ceph-blockpool-crs.yaml
  - ceph-objectstore-crs.yaml
  - ceph-filsystem-crs.yaml
  - storageclass.yaml