configuration:
  logLevel: debug
  # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
  # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
  backupStorageLocation:
    # name is the name of the backup storage location where backups should be stored. If a name is not provided,
    # a backup storage location will be created with the name "default". Optional.
    - name: cloudprovider-objectstorage
      # provider is the name for the backup storage location provider.
      provider: velero.io/aws
      # bucket is the name of the bucket to store backups in. Required.
      bucket: ${ARGOCD_ENV_object_storage_bucket}
      prefix: "backups"
      # default indicates this location is the default backup storage location. Optional.
      default: true
      # validationFrequency defines how frequently Velero should validate the object storage. Optional.
      accessMode: ReadWrite
      credential:
        key: ${ARGOCD_ENV_object_storage_secret_key}
        name: ${ARGOCD_ENV_object_storage_secret_name}
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        profile: default

      # annotations allows adding arbitrary annotations to this BackupStorageLocation resource. Optional.
      annotations: {}

  # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
  # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
  volumeSnapshotLocation:
    # name is the name of the volume snapshot location where snapshots are being taken. Required.
    - name: cloudprovider-objectstorage
      # provider is the name for the volume snapshot provider.
      provider: velero.io/aws
      credential:
        key: ${ARGOCD_ENV_object_storage_secret_key}
        name: ${ARGOCD_ENV_object_storage_secret_name}
      # Additional provider-specific configuration. See link above
      # for details of required/optional fields for your provider.
      config:
        profile: default
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:${ARGOCD_ENV_velero_plugin_version}
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
      - name: cloud-credentials
        mountPath: /credentials

credentials:
  useSecret: true
  existingSecret: ${ARGOCD_ENV_object_storage_secret_name}
  #extraSecretRef: ${ARGOCD_ENV_object_storage_secret_name}
